// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UralHiking.Database;

#nullable disable

namespace UralHiking.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20251104091229_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GearItemHikingRoute", b =>
                {
                    b.Property<int>("GearItemsId")
                        .HasColumnType("integer")
                        .HasColumnName("gear_items_id");

                    b.Property<int>("HikingRoutesId")
                        .HasColumnType("integer")
                        .HasColumnName("hiking_routes_id");

                    b.HasKey("GearItemsId", "HikingRoutesId")
                        .HasName("pk_gear_item_hiking_route");

                    b.HasIndex("HikingRoutesId")
                        .HasDatabaseName("ix_gear_item_hiking_route_hiking_routes_id");

                    b.ToTable("gear_item_hiking_route", (string)null);
                });

            modelBuilder.Entity("UralHiking.Models.Coordinate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("HikingRouteId")
                        .HasColumnType("integer")
                        .HasColumnName("hiking_route_id");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude")
                        .HasAnnotation("Relational:JsonPropertyName", "latitude");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude")
                        .HasAnnotation("Relational:JsonPropertyName", "longitude");

                    b.HasKey("Id")
                        .HasName("pk_coordinates");

                    b.HasIndex("HikingRouteId")
                        .HasDatabaseName("ix_coordinates_hiking_route_id");

                    b.ToTable("coordinates", (string)null);

                    b.HasAnnotation("Relational:JsonPropertyName", "coordinates");
                });

            modelBuilder.Entity("UralHiking.Models.GearItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text")
                        .HasAnnotation("Relational:JsonPropertyName", "text");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url")
                        .HasAnnotation("Relational:JsonPropertyName", "url");

                    b.HasKey("Id")
                        .HasName("pk_gear_items");

                    b.ToTable("gear_items", (string)null);
                });

            modelBuilder.Entity("UralHiking.Models.HikingRoute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AscentMeters")
                        .HasColumnType("integer")
                        .HasColumnName("ascent_meters")
                        .HasAnnotation("Relational:JsonPropertyName", "ascent_meters");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description")
                        .HasAnnotation("Relational:JsonPropertyName", "description");

                    b.Property<int>("DifficultyInternal")
                        .HasColumnType("integer")
                        .HasColumnName("difficulty_internal");

                    b.Property<int>("DistanceMeters")
                        .HasColumnType("integer")
                        .HasColumnName("distance_meters")
                        .HasAnnotation("Relational:JsonPropertyName", "distance_meters");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("duration_minutes")
                        .HasAnnotation("Relational:JsonPropertyName", "duration_minutes");

                    b.Property<string>("LocationName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("location_name")
                        .HasAnnotation("Relational:JsonPropertyName", "location_name");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name")
                        .HasAnnotation("Relational:JsonPropertyName", "name");

                    b.Property<string>("PhotoUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("photo_url")
                        .HasAnnotation("Relational:JsonPropertyName", "photo_url");

                    b.Property<double>("Rating")
                        .HasColumnType("double precision")
                        .HasColumnName("rating")
                        .HasAnnotation("Relational:JsonPropertyName", "rating");

                    b.Property<int>("ReviewCount")
                        .HasColumnType("integer")
                        .HasColumnName("review_count")
                        .HasAnnotation("Relational:JsonPropertyName", "review_count");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("short_description")
                        .HasAnnotation("Relational:JsonPropertyName", "short_description");

                    b.HasKey("Id")
                        .HasName("pk_hiking_routes");

                    b.ToTable("hiking_routes", (string)null);
                });

            modelBuilder.Entity("GearItemHikingRoute", b =>
                {
                    b.HasOne("UralHiking.Models.GearItem", null)
                        .WithMany()
                        .HasForeignKey("GearItemsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_gear_item_hiking_route_gear_items_gear_items_id");

                    b.HasOne("UralHiking.Models.HikingRoute", null)
                        .WithMany()
                        .HasForeignKey("HikingRoutesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_gear_item_hiking_route_hiking_routes_hiking_routes_id");
                });

            modelBuilder.Entity("UralHiking.Models.Coordinate", b =>
                {
                    b.HasOne("UralHiking.Models.HikingRoute", "HikingRoute")
                        .WithMany("Coordinates")
                        .HasForeignKey("HikingRouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_coordinates_hiking_routes_hiking_route_id");

                    b.Navigation("HikingRoute");
                });

            modelBuilder.Entity("UralHiking.Models.HikingRoute", b =>
                {
                    b.Navigation("Coordinates");
                });
#pragma warning restore 612, 618
        }
    }
}
